require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/picture_shots", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PictureShot. As you add validations to PictureShot, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PictureShot.create! valid_attributes
      get picture_shots_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      picture_shot = PictureShot.create! valid_attributes
      get picture_shot_url(picture_shot)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_picture_shot_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      picture_shot = PictureShot.create! valid_attributes
      get edit_picture_shot_url(picture_shot)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PictureShot" do
        expect {
          post picture_shots_url, params: { picture_shot: valid_attributes }
        }.to change(PictureShot, :count).by(1)
      end

      it "redirects to the created picture_shot" do
        post picture_shots_url, params: { picture_shot: valid_attributes }
        expect(response).to redirect_to(picture_shot_url(PictureShot.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PictureShot" do
        expect {
          post picture_shots_url, params: { picture_shot: invalid_attributes }
        }.to change(PictureShot, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post picture_shots_url, params: { picture_shot: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested picture_shot" do
        picture_shot = PictureShot.create! valid_attributes
        patch picture_shot_url(picture_shot), params: { picture_shot: new_attributes }
        picture_shot.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the picture_shot" do
        picture_shot = PictureShot.create! valid_attributes
        patch picture_shot_url(picture_shot), params: { picture_shot: new_attributes }
        picture_shot.reload
        expect(response).to redirect_to(picture_shot_url(picture_shot))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        picture_shot = PictureShot.create! valid_attributes
        patch picture_shot_url(picture_shot), params: { picture_shot: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested picture_shot" do
      picture_shot = PictureShot.create! valid_attributes
      expect {
        delete picture_shot_url(picture_shot)
      }.to change(PictureShot, :count).by(-1)
    end

    it "redirects to the picture_shots list" do
      picture_shot = PictureShot.create! valid_attributes
      delete picture_shot_url(picture_shot)
      expect(response).to redirect_to(picture_shots_url)
    end
  end
end
